---
- hosts: localhost
  become_method: sudo
  become: true

  tasks:
  - name: Create Folder opt/afyastat/medic
    file: 
       path: /opt/afyastat/
       owner: root
       group: root
       mode: 0777 
       recurse: yes
       state: directory
       
  - name: Copy installation Package 
    shell: "cp -r medic /opt/afyastat"
    
  - name: Assign rights to directoty 
    shell: "chmod -R 0777 /opt/afyastat"
       
  - name: install curl 
    apt:
        name: curl
        state: present
        
  - name: apt update
    apt:
       update-cache: yes
       
  - name: apt-get install apt-transport-https ca-certificates curl software-properties-common
    apt:  
    
  - name: Install docker packages
    remote_user: ubuntu
    apt:
      name: "{{ item }}"
      state: present
      update_cache: yes
    with_items:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
    tags:
      - docker
  - name: Add Docker s official GPG key
    remote_user: ubuntu
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present
    tags:
      - docker
  - name: Verify that we have the key with the fingerprint
    remote_user: ubuntu
    apt_key:
      id: 0EBFCD88
      state: present
    tags:
      - docker
  - name: Set up the stable repository
    remote_user: ubuntu
    apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable
      state: present
      update_cache: yes
    tags:
      - docker
  - name: Update apt packages
    remote_user: ubuntu
    apt:
      update_cache: yes
    tags:
      - docker
  - name: Install docker
    remote_user: ubuntu
    apt:
      name: docker-ce
      state: present
      update_cache: yes
    #notify: Start docker on boot
    tags:
      - docker
  - name: Add remote "ubuntu" user to "docker" group
    remote_user: ubuntu
    user:
      name: "ubuntu"
      group: "docker"
      append: yes
    tags:
      - docker
  - name: Install docker-compose
    remote_user: ubuntu
    get_url: 
      url : https://github.com/docker/compose/releases/download/1.25.1-rc1/docker-compose-Linux-x86_64
      dest: /usr/local/bin/docker-compose
      mode: 'u+x,g+x'
      
  - name: Installing Pi-Hole
    become: true
    shell:
        cmd: "docker-compose -f pi-hole-docker-compose.yml up --detach"
        chdir: /opt/afyastat/medic
        
  - name: Set DOCKER_COUCHDB_ADMIN_PASSWORD
    shell: "echo $DOCKER_COUCHDB_ADMIN_PASSWORD"
    environment:
        DOCKER_COUCHDB_ADMIN_PASSWORD: cb6f4d4b-73cc-4c42-97cb-0db5a631190a

  - name: Echo DOCKER_COUCHDB_ADMIN_PASSWORD 
    shell: "echo $DOCKER_COUCHDB_ADMIN_PASSWORD"
    
  - name: Set COUCH_URL
    shell: "echo $COUCH_URL"
    environment:
        COUCH_URL: http://medic:cb6f4d4b-73cc-4c42-97cb-0db5a631190a@localhost:5988/medic

  - name: Echo COUCH_URL
    shell: "echo $COUCH_URL"  
    
  - name: Set COUCH_NODE_NAME
    shell: "echo $COUCH_NODE_NAME"
    environment:
        COUCH_NODE_NAME: onode@nohost

  - name: Echo COUCH_NODE_NAME
    shell: "echo $COUCH_NODE_NAME" 
    
  - name: Installing Medic-OS
    become: true
    shell:
        cmd: "docker-compose -f cht-docker-compose-local-host.yml up --detach"
        chdir: /opt/afyastat/medic
        
  - name: Copy nginx File to Medic-os Container
    #delay copying for 30 seconds
    shell: docker cp  /opt/afyastat/medic/nginx.conf medic-os:/srv/settings/medic-core/nginx/nginx.conf
           
  - name: Get all containers for restart
    command: docker ps -a 
    register: docker_images

  - name: Restarting Medic-os container
    shell: docker restart medic-os

  - name: apt update
    apt:
       update-cache: yes

  - name: installing nodejs
    shell: apt -y install nodejs

  - name: installing NPM
    shell: apt -y install npm
    
  - name: Uploading AfyaStat Forms
    shell: npm install -g medic-conf@3.6.0 
  
  - name: Initalling pip AfyaStat Forms
    shell: apt-get install -y python3-pip  
    
    
  - name: Uploading AfyaStat Forms
    shell: python3 -m pip install git+https://github.com/medic/pyxform.git@medic-conf-1.17#egg=pyxform-medic
    
  - name: Waiting for AfyaStat to Start. Please Wait !!!
    uri:
     url: "http://localhost:5988"
     status_code: [200,301]
    register: result
    until: result.status == 200
    retries: 20
    delay: 30

  - name: Uploading AfyaStat Forms
    command: medic-conf --url=http://medic:cb6f4d4b-73cc-4c42-97cb-0db5a631190a@localhost:5988 upload-app-settings delete-all-forms upload-app-forms upload-contact-forms upload-resources upload-custom-translations --accept-self-signed-certs
    args:
     chdir: /opt/afyastat/medic/AfyaStatForms

        
  - name: "Show Network Interfaces"
    command: hostname -I
    #register: details
        
  
